/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.techsocialist.servicebuilder.model.VideoRegisterEntry;
import com.techsocialist.servicebuilder.model.VideoRegisterEntryContentBlobModel;
import com.techsocialist.servicebuilder.model.VideoRegisterEntryModel;
import com.techsocialist.servicebuilder.service.VideoRegisterEntryLocalServiceUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VideoRegisterEntry service. Represents a row in the &quot;video_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VideoRegisterEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoRegisterEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VideoRegisterEntryImpl
 * @generated
 */
public class VideoRegisterEntryModelImpl
	extends BaseModelImpl<VideoRegisterEntry>
	implements VideoRegisterEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video register entry model instance should use the <code>VideoRegisterEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "video_register";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"productionHouseEntryId", Types.BIGINT},
		{"content", Types.BLOB}, {"type_", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"createdBy", Types.VARCHAR},
		{"modifiedBy", Types.VARCHAR}, {"createdDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productionHouseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("content", Types.BLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table video_register (id_ LONG not null primary key,productionHouseEntryId LONG,content BLOB,type_ VARCHAR(75) null,status VARCHAR(75) null,createdBy VARCHAR(75) null,modifiedBy VARCHAR(75) null,createdDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table video_register";

	public static final String ORDER_BY_JPQL =
		" ORDER BY videoRegisterEntry.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY video_register.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public VideoRegisterEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VideoRegisterEntry.class;
	}

	@Override
	public String getModelClassName() {
		return VideoRegisterEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VideoRegisterEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VideoRegisterEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VideoRegisterEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((VideoRegisterEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VideoRegisterEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VideoRegisterEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VideoRegisterEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VideoRegisterEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VideoRegisterEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, VideoRegisterEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			VideoRegisterEntry.class.getClassLoader(), VideoRegisterEntry.class,
			ModelWrapper.class);

		try {
			Constructor<VideoRegisterEntry> constructor =
				(Constructor<VideoRegisterEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<VideoRegisterEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VideoRegisterEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VideoRegisterEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<VideoRegisterEntry, Object>>();
		Map<String, BiConsumer<VideoRegisterEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<VideoRegisterEntry, ?>>();

		attributeGetterFunctions.put("id", VideoRegisterEntry::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<VideoRegisterEntry, Long>)VideoRegisterEntry::setId);
		attributeGetterFunctions.put(
			"productionHouseEntryId",
			VideoRegisterEntry::getProductionHouseEntryId);
		attributeSetterBiConsumers.put(
			"productionHouseEntryId",
			(BiConsumer<VideoRegisterEntry, Long>)
				VideoRegisterEntry::setProductionHouseEntryId);
		attributeGetterFunctions.put("content", VideoRegisterEntry::getContent);
		attributeSetterBiConsumers.put(
			"content",
			(BiConsumer<VideoRegisterEntry, Blob>)
				VideoRegisterEntry::setContent);
		attributeGetterFunctions.put("type", VideoRegisterEntry::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<VideoRegisterEntry, String>)
				VideoRegisterEntry::setType);
		attributeGetterFunctions.put("status", VideoRegisterEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<VideoRegisterEntry, String>)
				VideoRegisterEntry::setStatus);
		attributeGetterFunctions.put(
			"createdBy", VideoRegisterEntry::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<VideoRegisterEntry, String>)
				VideoRegisterEntry::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedBy", VideoRegisterEntry::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<VideoRegisterEntry, String>)
				VideoRegisterEntry::setModifiedBy);
		attributeGetterFunctions.put(
			"createdDate", VideoRegisterEntry::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<VideoRegisterEntry, Date>)
				VideoRegisterEntry::setCreatedDate);
		attributeGetterFunctions.put(
			"modifiedDate", VideoRegisterEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VideoRegisterEntry, Date>)
				VideoRegisterEntry::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getProductionHouseEntryId() {
		return _productionHouseEntryId;
	}

	@Override
	public void setProductionHouseEntryId(long productionHouseEntryId) {
		_productionHouseEntryId = productionHouseEntryId;
	}

	@Override
	public Blob getContent() {
		if (_contentBlobModel == null) {
			try {
				_contentBlobModel =
					VideoRegisterEntryLocalServiceUtil.getContentBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_contentBlobModel != null) {
			blob = _contentBlobModel.getContentBlob();
		}

		return blob;
	}

	@Override
	public void setContent(Blob content) {
		if (_contentBlobModel == null) {
			_contentBlobModel = new VideoRegisterEntryContentBlobModel(
				getPrimaryKey(), content);
		}
		else {
			_contentBlobModel.setContentBlob(content);
		}
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return "";
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public String getModifiedBy() {
		if (_modifiedBy == null) {
			return "";
		}
		else {
			return _modifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, VideoRegisterEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VideoRegisterEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VideoRegisterEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VideoRegisterEntryImpl videoRegisterEntryImpl =
			new VideoRegisterEntryImpl();

		videoRegisterEntryImpl.setId(getId());
		videoRegisterEntryImpl.setProductionHouseEntryId(
			getProductionHouseEntryId());
		videoRegisterEntryImpl.setType(getType());
		videoRegisterEntryImpl.setStatus(getStatus());
		videoRegisterEntryImpl.setCreatedBy(getCreatedBy());
		videoRegisterEntryImpl.setModifiedBy(getModifiedBy());
		videoRegisterEntryImpl.setCreatedDate(getCreatedDate());
		videoRegisterEntryImpl.setModifiedDate(getModifiedDate());

		videoRegisterEntryImpl.resetOriginalValues();

		return videoRegisterEntryImpl;
	}

	@Override
	public int compareTo(VideoRegisterEntry videoRegisterEntry) {
		long primaryKey = videoRegisterEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VideoRegisterEntry)) {
			return false;
		}

		VideoRegisterEntry videoRegisterEntry = (VideoRegisterEntry)obj;

		long primaryKey = videoRegisterEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		VideoRegisterEntryModelImpl videoRegisterEntryModelImpl = this;

		videoRegisterEntryModelImpl._contentBlobModel = null;
	}

	@Override
	public CacheModel<VideoRegisterEntry> toCacheModel() {
		VideoRegisterEntryCacheModel videoRegisterEntryCacheModel =
			new VideoRegisterEntryCacheModel();

		videoRegisterEntryCacheModel.id = getId();

		videoRegisterEntryCacheModel.productionHouseEntryId =
			getProductionHouseEntryId();

		videoRegisterEntryCacheModel.type = getType();

		String type = videoRegisterEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			videoRegisterEntryCacheModel.type = null;
		}

		videoRegisterEntryCacheModel.status = getStatus();

		String status = videoRegisterEntryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			videoRegisterEntryCacheModel.status = null;
		}

		videoRegisterEntryCacheModel.createdBy = getCreatedBy();

		String createdBy = videoRegisterEntryCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			videoRegisterEntryCacheModel.createdBy = null;
		}

		videoRegisterEntryCacheModel.modifiedBy = getModifiedBy();

		String modifiedBy = videoRegisterEntryCacheModel.modifiedBy;

		if ((modifiedBy != null) && (modifiedBy.length() == 0)) {
			videoRegisterEntryCacheModel.modifiedBy = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			videoRegisterEntryCacheModel.createdDate = createdDate.getTime();
		}
		else {
			videoRegisterEntryCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			videoRegisterEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			videoRegisterEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return videoRegisterEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", productionHouseEntryId=");
		sb.append(getProductionHouseEntryId());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.techsocialist.servicebuilder.model.VideoRegisterEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productionHouseEntryId</column-name><column-value><![CDATA[");
		sb.append(getProductionHouseEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VideoRegisterEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id;
	private long _productionHouseEntryId;
	private VideoRegisterEntryContentBlobModel _contentBlobModel;
	private String _type;
	private String _status;
	private String _createdBy;
	private String _modifiedBy;
	private Date _createdDate;
	private Date _modifiedDate;
	private VideoRegisterEntry _escapedModel;

}