/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.techsocialist.servicebuilder.model.VideoEntry;
import com.techsocialist.servicebuilder.model.VideoEntryContentBlobModel;
import com.techsocialist.servicebuilder.model.VideoEntryModel;
import com.techsocialist.servicebuilder.service.VideoEntryLocalServiceUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VideoEntry service. Represents a row in the &quot;video_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VideoEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VideoEntryImpl
 * @generated
 */
public class VideoEntryModelImpl
	extends BaseModelImpl<VideoEntry> implements VideoEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video entry model instance should use the <code>VideoEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "video_register";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"productionHouseEntryId", Types.BIGINT},
		{"content", Types.BLOB}, {"type_", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"createdBy", Types.VARCHAR},
		{"modifiedBy", Types.VARCHAR}, {"createdDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productionHouseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("content", Types.BLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table video_register (id_ LONG not null primary key,productionHouseEntryId LONG,content BLOB,type_ VARCHAR(75) null,status VARCHAR(75) null,createdBy VARCHAR(75) null,modifiedBy VARCHAR(75) null,createdDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table video_register";

	public static final String ORDER_BY_JPQL = " ORDER BY videoEntry.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY video_register.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public VideoEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VideoEntry.class;
	}

	@Override
	public String getModelClassName() {
		return VideoEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VideoEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VideoEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VideoEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((VideoEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VideoEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VideoEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VideoEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VideoEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VideoEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, VideoEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			VideoEntry.class.getClassLoader(), VideoEntry.class,
			ModelWrapper.class);

		try {
			Constructor<VideoEntry> constructor =
				(Constructor<VideoEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<VideoEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<VideoEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<VideoEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<VideoEntry, Object>>();
		Map<String, BiConsumer<VideoEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<VideoEntry, ?>>();

		attributeGetterFunctions.put("id", VideoEntry::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<VideoEntry, Long>)VideoEntry::setId);
		attributeGetterFunctions.put(
			"productionHouseEntryId", VideoEntry::getProductionHouseEntryId);
		attributeSetterBiConsumers.put(
			"productionHouseEntryId",
			(BiConsumer<VideoEntry, Long>)
				VideoEntry::setProductionHouseEntryId);
		attributeGetterFunctions.put("content", VideoEntry::getContent);
		attributeSetterBiConsumers.put(
			"content", (BiConsumer<VideoEntry, Blob>)VideoEntry::setContent);
		attributeGetterFunctions.put("type", VideoEntry::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<VideoEntry, String>)VideoEntry::setType);
		attributeGetterFunctions.put("status", VideoEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<VideoEntry, String>)VideoEntry::setStatus);
		attributeGetterFunctions.put("createdBy", VideoEntry::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<VideoEntry, String>)VideoEntry::setCreatedBy);
		attributeGetterFunctions.put("modifiedBy", VideoEntry::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<VideoEntry, String>)VideoEntry::setModifiedBy);
		attributeGetterFunctions.put("createdDate", VideoEntry::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<VideoEntry, Date>)VideoEntry::setCreatedDate);
		attributeGetterFunctions.put(
			"modifiedDate", VideoEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<VideoEntry, Date>)VideoEntry::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getProductionHouseEntryId() {
		return _productionHouseEntryId;
	}

	@Override
	public void setProductionHouseEntryId(long productionHouseEntryId) {
		_productionHouseEntryId = productionHouseEntryId;
	}

	@Override
	public Blob getContent() {
		if (_contentBlobModel == null) {
			try {
				_contentBlobModel =
					VideoEntryLocalServiceUtil.getContentBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_contentBlobModel != null) {
			blob = _contentBlobModel.getContentBlob();
		}

		return blob;
	}

	@Override
	public void setContent(Blob content) {
		if (_contentBlobModel == null) {
			_contentBlobModel = new VideoEntryContentBlobModel(
				getPrimaryKey(), content);
		}
		else {
			_contentBlobModel.setContentBlob(content);
		}
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return "";
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public String getModifiedBy() {
		if (_modifiedBy == null) {
			return "";
		}
		else {
			return _modifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, VideoEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VideoEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VideoEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VideoEntryImpl videoEntryImpl = new VideoEntryImpl();

		videoEntryImpl.setId(getId());
		videoEntryImpl.setProductionHouseEntryId(getProductionHouseEntryId());
		videoEntryImpl.setType(getType());
		videoEntryImpl.setStatus(getStatus());
		videoEntryImpl.setCreatedBy(getCreatedBy());
		videoEntryImpl.setModifiedBy(getModifiedBy());
		videoEntryImpl.setCreatedDate(getCreatedDate());
		videoEntryImpl.setModifiedDate(getModifiedDate());

		videoEntryImpl.resetOriginalValues();

		return videoEntryImpl;
	}

	@Override
	public int compareTo(VideoEntry videoEntry) {
		long primaryKey = videoEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VideoEntry)) {
			return false;
		}

		VideoEntry videoEntry = (VideoEntry)obj;

		long primaryKey = videoEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		VideoEntryModelImpl videoEntryModelImpl = this;

		videoEntryModelImpl._contentBlobModel = null;
	}

	@Override
	public CacheModel<VideoEntry> toCacheModel() {
		VideoEntryCacheModel videoEntryCacheModel = new VideoEntryCacheModel();

		videoEntryCacheModel.id = getId();

		videoEntryCacheModel.productionHouseEntryId =
			getProductionHouseEntryId();

		videoEntryCacheModel.type = getType();

		String type = videoEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			videoEntryCacheModel.type = null;
		}

		videoEntryCacheModel.status = getStatus();

		String status = videoEntryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			videoEntryCacheModel.status = null;
		}

		videoEntryCacheModel.createdBy = getCreatedBy();

		String createdBy = videoEntryCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			videoEntryCacheModel.createdBy = null;
		}

		videoEntryCacheModel.modifiedBy = getModifiedBy();

		String modifiedBy = videoEntryCacheModel.modifiedBy;

		if ((modifiedBy != null) && (modifiedBy.length() == 0)) {
			videoEntryCacheModel.modifiedBy = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			videoEntryCacheModel.createdDate = createdDate.getTime();
		}
		else {
			videoEntryCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			videoEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			videoEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return videoEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", productionHouseEntryId=");
		sb.append(getProductionHouseEntryId());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.techsocialist.servicebuilder.model.VideoEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productionHouseEntryId</column-name><column-value><![CDATA[");
		sb.append(getProductionHouseEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VideoEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id;
	private long _productionHouseEntryId;
	private VideoEntryContentBlobModel _contentBlobModel;
	private String _type;
	private String _status;
	private String _createdBy;
	private String _modifiedBy;
	private Date _createdDate;
	private Date _modifiedDate;
	private VideoEntry _escapedModel;

}