/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.techsocialist.servicebuilder.model.Video;
import com.techsocialist.servicebuilder.model.VideoContentBlobModel;
import com.techsocialist.servicebuilder.model.VideoModel;
import com.techsocialist.servicebuilder.model.VideoThumbnailBlobModel;
import com.techsocialist.servicebuilder.service.VideoLocalServiceUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Video service. Represents a row in the &quot;video_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VideoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VideoImpl
 * @generated
 */
public class VideoModelImpl extends BaseModelImpl<Video> implements VideoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video model instance should use the <code>Video</code> interface instead.
	 */
	public static final String TABLE_NAME = "video_register";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"productionHouseId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"thumbnail", Types.BLOB},
		{"content", Types.BLOB}, {"type_", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"ticketPrice", Types.DOUBLE},
		{"publishDateTime", Types.BIGINT}, {"createdBy", Types.VARCHAR},
		{"modifiedBy", Types.VARCHAR}, {"createdDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productionHouseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("thumbnail", Types.BLOB);
		TABLE_COLUMNS_MAP.put("content", Types.BLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ticketPrice", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("publishDateTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table video_register (id_ LONG not null primary key,productionHouseId LONG,name VARCHAR(75) null,thumbnail BLOB,content BLOB,type_ VARCHAR(75) null,status VARCHAR(75) null,ticketPrice DOUBLE,publishDateTime LONG,createdBy VARCHAR(75) null,modifiedBy VARCHAR(75) null,createdDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table video_register";

	public static final String ORDER_BY_JPQL = " ORDER BY video.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY video_register.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public VideoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Video.class;
	}

	@Override
	public String getModelClassName() {
		return Video.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Video, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Video, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Video, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Video)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Video, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Video, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Video)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Video, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Video, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Video>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Video.class.getClassLoader(), Video.class, ModelWrapper.class);

		try {
			Constructor<Video> constructor =
				(Constructor<Video>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Video, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Video, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Video, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Video, Object>>();
		Map<String, BiConsumer<Video, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Video, ?>>();

		attributeGetterFunctions.put("id", Video::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Video, Long>)Video::setId);
		attributeGetterFunctions.put(
			"productionHouseId", Video::getProductionHouseId);
		attributeSetterBiConsumers.put(
			"productionHouseId",
			(BiConsumer<Video, Long>)Video::setProductionHouseId);
		attributeGetterFunctions.put("name", Video::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Video, String>)Video::setName);
		attributeGetterFunctions.put("thumbnail", Video::getThumbnail);
		attributeSetterBiConsumers.put(
			"thumbnail", (BiConsumer<Video, Blob>)Video::setThumbnail);
		attributeGetterFunctions.put("content", Video::getContent);
		attributeSetterBiConsumers.put(
			"content", (BiConsumer<Video, Blob>)Video::setContent);
		attributeGetterFunctions.put("type", Video::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<Video, String>)Video::setType);
		attributeGetterFunctions.put("status", Video::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Video, String>)Video::setStatus);
		attributeGetterFunctions.put("ticketPrice", Video::getTicketPrice);
		attributeSetterBiConsumers.put(
			"ticketPrice", (BiConsumer<Video, Double>)Video::setTicketPrice);
		attributeGetterFunctions.put(
			"publishDateTime", Video::getPublishDateTime);
		attributeSetterBiConsumers.put(
			"publishDateTime",
			(BiConsumer<Video, Long>)Video::setPublishDateTime);
		attributeGetterFunctions.put("createdBy", Video::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy", (BiConsumer<Video, String>)Video::setCreatedBy);
		attributeGetterFunctions.put("modifiedBy", Video::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy", (BiConsumer<Video, String>)Video::setModifiedBy);
		attributeGetterFunctions.put("createdDate", Video::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate", (BiConsumer<Video, Date>)Video::setCreatedDate);
		attributeGetterFunctions.put("modifiedDate", Video::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Video, Date>)Video::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getProductionHouseId() {
		return _productionHouseId;
	}

	@Override
	public void setProductionHouseId(long productionHouseId) {
		_productionHouseId = productionHouseId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public Blob getThumbnail() {
		if (_thumbnailBlobModel == null) {
			try {
				_thumbnailBlobModel =
					VideoLocalServiceUtil.getThumbnailBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_thumbnailBlobModel != null) {
			blob = _thumbnailBlobModel.getThumbnailBlob();
		}

		return blob;
	}

	@Override
	public void setThumbnail(Blob thumbnail) {
		if (_thumbnailBlobModel == null) {
			_thumbnailBlobModel = new VideoThumbnailBlobModel(
				getPrimaryKey(), thumbnail);
		}
		else {
			_thumbnailBlobModel.setThumbnailBlob(thumbnail);
		}
	}

	@Override
	public Blob getContent() {
		if (_contentBlobModel == null) {
			try {
				_contentBlobModel = VideoLocalServiceUtil.getContentBlobModel(
					getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_contentBlobModel != null) {
			blob = _contentBlobModel.getContentBlob();
		}

		return blob;
	}

	@Override
	public void setContent(Blob content) {
		if (_contentBlobModel == null) {
			_contentBlobModel = new VideoContentBlobModel(
				getPrimaryKey(), content);
		}
		else {
			_contentBlobModel.setContentBlob(content);
		}
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public double getTicketPrice() {
		return _ticketPrice;
	}

	@Override
	public void setTicketPrice(double ticketPrice) {
		_ticketPrice = ticketPrice;
	}

	@Override
	public long getPublishDateTime() {
		return _publishDateTime;
	}

	@Override
	public void setPublishDateTime(long publishDateTime) {
		_publishDateTime = publishDateTime;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return "";
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public String getModifiedBy() {
		if (_modifiedBy == null) {
			return "";
		}
		else {
			return _modifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Video.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Video toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Video>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VideoImpl videoImpl = new VideoImpl();

		videoImpl.setId(getId());
		videoImpl.setProductionHouseId(getProductionHouseId());
		videoImpl.setName(getName());
		videoImpl.setType(getType());
		videoImpl.setStatus(getStatus());
		videoImpl.setTicketPrice(getTicketPrice());
		videoImpl.setPublishDateTime(getPublishDateTime());
		videoImpl.setCreatedBy(getCreatedBy());
		videoImpl.setModifiedBy(getModifiedBy());
		videoImpl.setCreatedDate(getCreatedDate());
		videoImpl.setModifiedDate(getModifiedDate());

		videoImpl.resetOriginalValues();

		return videoImpl;
	}

	@Override
	public int compareTo(Video video) {
		long primaryKey = video.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Video)) {
			return false;
		}

		Video video = (Video)obj;

		long primaryKey = video.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		VideoModelImpl videoModelImpl = this;

		videoModelImpl._thumbnailBlobModel = null;

		videoModelImpl._contentBlobModel = null;
	}

	@Override
	public CacheModel<Video> toCacheModel() {
		VideoCacheModel videoCacheModel = new VideoCacheModel();

		videoCacheModel.id = getId();

		videoCacheModel.productionHouseId = getProductionHouseId();

		videoCacheModel.name = getName();

		String name = videoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			videoCacheModel.name = null;
		}

		videoCacheModel.type = getType();

		String type = videoCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			videoCacheModel.type = null;
		}

		videoCacheModel.status = getStatus();

		String status = videoCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			videoCacheModel.status = null;
		}

		videoCacheModel.ticketPrice = getTicketPrice();

		videoCacheModel.publishDateTime = getPublishDateTime();

		videoCacheModel.createdBy = getCreatedBy();

		String createdBy = videoCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			videoCacheModel.createdBy = null;
		}

		videoCacheModel.modifiedBy = getModifiedBy();

		String modifiedBy = videoCacheModel.modifiedBy;

		if ((modifiedBy != null) && (modifiedBy.length() == 0)) {
			videoCacheModel.modifiedBy = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			videoCacheModel.createdDate = createdDate.getTime();
		}
		else {
			videoCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			videoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			videoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return videoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", productionHouseId=");
		sb.append(getProductionHouseId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", ticketPrice=");
		sb.append(getTicketPrice());
		sb.append(", publishDateTime=");
		sb.append(getPublishDateTime());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.techsocialist.servicebuilder.model.Video");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productionHouseId</column-name><column-value><![CDATA[");
		sb.append(getProductionHouseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketPrice</column-name><column-value><![CDATA[");
		sb.append(getTicketPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishDateTime</column-name><column-value><![CDATA[");
		sb.append(getPublishDateTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Video>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id;
	private long _productionHouseId;
	private String _name;
	private VideoThumbnailBlobModel _thumbnailBlobModel;
	private VideoContentBlobModel _contentBlobModel;
	private String _type;
	private String _status;
	private double _ticketPrice;
	private long _publishDateTime;
	private String _createdBy;
	private String _modifiedBy;
	private Date _createdDate;
	private Date _modifiedDate;
	private Video _escapedModel;

}