/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductionHouse service. Represents a row in the &quot;production_house_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.techsocialist.servicebuilder.model.impl.ProductionHouseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.techsocialist.servicebuilder.model.impl.ProductionHouseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductionHouse
 * @generated
 */
@ProviderType
public interface ProductionHouseModel extends BaseModel<ProductionHouse> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a production house model instance should use the {@link ProductionHouse} interface instead.
	 */

	/**
	 * Returns the primary key of this production house.
	 *
	 * @return the primary key of this production house
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this production house.
	 *
	 * @param primaryKey the primary key of this production house
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this production house.
	 *
	 * @return the ID of this production house
	 */
	public long getId();

	/**
	 * Sets the ID of this production house.
	 *
	 * @param id the ID of this production house
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this production house.
	 *
	 * @return the user ID of this production house
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this production house.
	 *
	 * @param userId the user ID of this production house
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this production house.
	 *
	 * @return the user uuid of this production house
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this production house.
	 *
	 * @param userUuid the user uuid of this production house
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this production house.
	 *
	 * @return the name of this production house
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this production house.
	 *
	 * @param name the name of this production house
	 */
	public void setName(String name);

	/**
	 * Returns the cin of this production house.
	 *
	 * @return the cin of this production house
	 */
	@AutoEscape
	public String getCin();

	/**
	 * Sets the cin of this production house.
	 *
	 * @param cin the cin of this production house
	 */
	public void setCin(String cin);

	/**
	 * Returns the logo of this production house.
	 *
	 * @return the logo of this production house
	 */
	public Blob getLogo();

	/**
	 * Sets the logo of this production house.
	 *
	 * @param logo the logo of this production house
	 */
	public void setLogo(Blob logo);

	/**
	 * Returns the banner of this production house.
	 *
	 * @return the banner of this production house
	 */
	public Blob getBanner();

	/**
	 * Sets the banner of this production house.
	 *
	 * @param banner the banner of this production house
	 */
	public void setBanner(Blob banner);

	/**
	 * Returns the landline of this production house.
	 *
	 * @return the landline of this production house
	 */
	@AutoEscape
	public String getLandline();

	/**
	 * Sets the landline of this production house.
	 *
	 * @param landline the landline of this production house
	 */
	public void setLandline(String landline);

	/**
	 * Returns the website url of this production house.
	 *
	 * @return the website url of this production house
	 */
	@AutoEscape
	public String getWebsiteUrl();

	/**
	 * Sets the website url of this production house.
	 *
	 * @param websiteUrl the website url of this production house
	 */
	public void setWebsiteUrl(String websiteUrl);

	/**
	 * Returns the address line1 of this production house.
	 *
	 * @return the address line1 of this production house
	 */
	@AutoEscape
	public String getAddressLine1();

	/**
	 * Sets the address line1 of this production house.
	 *
	 * @param addressLine1 the address line1 of this production house
	 */
	public void setAddressLine1(String addressLine1);

	/**
	 * Returns the address line2 of this production house.
	 *
	 * @return the address line2 of this production house
	 */
	@AutoEscape
	public String getAddressLine2();

	/**
	 * Sets the address line2 of this production house.
	 *
	 * @param addressLine2 the address line2 of this production house
	 */
	public void setAddressLine2(String addressLine2);

	/**
	 * Returns the address line3 of this production house.
	 *
	 * @return the address line3 of this production house
	 */
	@AutoEscape
	public String getAddressLine3();

	/**
	 * Sets the address line3 of this production house.
	 *
	 * @param addressLine3 the address line3 of this production house
	 */
	public void setAddressLine3(String addressLine3);

	/**
	 * Returns the place of this production house.
	 *
	 * @return the place of this production house
	 */
	@AutoEscape
	public String getPlace();

	/**
	 * Sets the place of this production house.
	 *
	 * @param place the place of this production house
	 */
	public void setPlace(String place);

	/**
	 * Returns the state of this production house.
	 *
	 * @return the state of this production house
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this production house.
	 *
	 * @param state the state of this production house
	 */
	public void setState(String state);

	/**
	 * Returns the country of this production house.
	 *
	 * @return the country of this production house
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this production house.
	 *
	 * @param country the country of this production house
	 */
	public void setCountry(String country);

	/**
	 * Returns the pincode of this production house.
	 *
	 * @return the pincode of this production house
	 */
	@AutoEscape
	public String getPincode();

	/**
	 * Sets the pincode of this production house.
	 *
	 * @param pincode the pincode of this production house
	 */
	public void setPincode(String pincode);

	/**
	 * Returns the status of this production house.
	 *
	 * @return the status of this production house
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this production house.
	 *
	 * @param status the status of this production house
	 */
	public void setStatus(String status);

	/**
	 * Returns the contact person first name of this production house.
	 *
	 * @return the contact person first name of this production house
	 */
	@AutoEscape
	public String getContactPersonFirstName();

	/**
	 * Sets the contact person first name of this production house.
	 *
	 * @param contactPersonFirstName the contact person first name of this production house
	 */
	public void setContactPersonFirstName(String contactPersonFirstName);

	/**
	 * Returns the contact person last name name of this production house.
	 *
	 * @return the contact person last name name of this production house
	 */
	@AutoEscape
	public String getContactPersonLastNameName();

	/**
	 * Sets the contact person last name name of this production house.
	 *
	 * @param contactPersonLastNameName the contact person last name name of this production house
	 */
	public void setContactPersonLastNameName(String contactPersonLastNameName);

	/**
	 * Returns the contact person mobile of this production house.
	 *
	 * @return the contact person mobile of this production house
	 */
	@AutoEscape
	public String getContactPersonMobile();

	/**
	 * Sets the contact person mobile of this production house.
	 *
	 * @param contactPersonMobile the contact person mobile of this production house
	 */
	public void setContactPersonMobile(String contactPersonMobile);

	/**
	 * Returns the contact person email of this production house.
	 *
	 * @return the contact person email of this production house
	 */
	@AutoEscape
	public String getContactPersonEmail();

	/**
	 * Sets the contact person email of this production house.
	 *
	 * @param contactPersonEmail the contact person email of this production house
	 */
	public void setContactPersonEmail(String contactPersonEmail);

	/**
	 * Returns the user name of this production house.
	 *
	 * @return the user name of this production house
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this production house.
	 *
	 * @param userName the user name of this production house
	 */
	public void setUserName(String userName);

	/**
	 * Returns the password of this production house.
	 *
	 * @return the password of this production house
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this production house.
	 *
	 * @param password the password of this production house
	 */
	public void setPassword(String password);

	/**
	 * Returns the created by of this production house.
	 *
	 * @return the created by of this production house
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this production house.
	 *
	 * @param createdBy the created by of this production house
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified by of this production house.
	 *
	 * @return the modified by of this production house
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this production house.
	 *
	 * @param modifiedBy the modified by of this production house
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the created date of this production house.
	 *
	 * @return the created date of this production house
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this production house.
	 *
	 * @param createdDate the created date of this production house
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this production house.
	 *
	 * @return the modified date of this production house
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this production house.
	 *
	 * @param modifiedDate the modified date of this production house
	 */
	public void setModifiedDate(Date modifiedDate);

}