/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketTax service. Represents a row in the &quot;ticket_tax_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.techsocialist.servicebuilder.model.impl.TicketTaxModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.techsocialist.servicebuilder.model.impl.TicketTaxImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketTax
 * @generated
 */
@ProviderType
public interface TicketTaxModel extends BaseModel<TicketTax> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket tax model instance should use the {@link TicketTax} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket tax.
	 *
	 * @return the primary key of this ticket tax
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket tax.
	 *
	 * @param primaryKey the primary key of this ticket tax
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ticket tax.
	 *
	 * @return the ID of this ticket tax
	 */
	public long getId();

	/**
	 * Sets the ID of this ticket tax.
	 *
	 * @param id the ID of this ticket tax
	 */
	public void setId(long id);

	/**
	 * Returns the percent of this ticket tax.
	 *
	 * @return the percent of this ticket tax
	 */
	public long getPercent();

	/**
	 * Sets the percent of this ticket tax.
	 *
	 * @param percent the percent of this ticket tax
	 */
	public void setPercent(long percent);

	/**
	 * Returns the enabled of this ticket tax.
	 *
	 * @return the enabled of this ticket tax
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this ticket tax is enabled.
	 *
	 * @return <code>true</code> if this ticket tax is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this ticket tax is enabled.
	 *
	 * @param enabled the enabled of this ticket tax
	 */
	public void setEnabled(boolean enabled);

	/**
	 * Returns the created by of this ticket tax.
	 *
	 * @return the created by of this ticket tax
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this ticket tax.
	 *
	 * @param createdBy the created by of this ticket tax
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified by of this ticket tax.
	 *
	 * @return the modified by of this ticket tax
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this ticket tax.
	 *
	 * @param modifiedBy the modified by of this ticket tax
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the created date of this ticket tax.
	 *
	 * @return the created date of this ticket tax
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ticket tax.
	 *
	 * @param createdDate the created date of this ticket tax
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this ticket tax.
	 *
	 * @return the modified date of this ticket tax
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket tax.
	 *
	 * @param modifiedDate the modified date of this ticket tax
	 */
	public void setModifiedDate(Date modifiedDate);

}