/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketPrice service. Represents a row in the &quot;ticket_price_register&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.techsocialist.servicebuilder.model.impl.TicketPriceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.techsocialist.servicebuilder.model.impl.TicketPriceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketPrice
 * @generated
 */
@ProviderType
public interface TicketPriceModel extends BaseModel<TicketPrice> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket price model instance should use the {@link TicketPrice} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket price.
	 *
	 * @return the primary key of this ticket price
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket price.
	 *
	 * @param primaryKey the primary key of this ticket price
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ticket price.
	 *
	 * @return the ID of this ticket price
	 */
	public long getId();

	/**
	 * Sets the ID of this ticket price.
	 *
	 * @param id the ID of this ticket price
	 */
	public void setId(long id);

	/**
	 * Returns the price of this ticket price.
	 *
	 * @return the price of this ticket price
	 */
	public long getPrice();

	/**
	 * Sets the price of this ticket price.
	 *
	 * @param price the price of this ticket price
	 */
	public void setPrice(long price);

	/**
	 * Returns the created by of this ticket price.
	 *
	 * @return the created by of this ticket price
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this ticket price.
	 *
	 * @param createdBy the created by of this ticket price
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified by of this ticket price.
	 *
	 * @return the modified by of this ticket price
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this ticket price.
	 *
	 * @param modifiedBy the modified by of this ticket price
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the created date of this ticket price.
	 *
	 * @return the created date of this ticket price
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ticket price.
	 *
	 * @param createdDate the created date of this ticket price
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this ticket price.
	 *
	 * @return the modified date of this ticket price
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket price.
	 *
	 * @param modifiedDate the modified date of this ticket price
	 */
	public void setModifiedDate(Date modifiedDate);

}