/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.techsocialist.servicebuilder.service.base;

import com.liferay.petra.io.AutoDeleteFileInputStream;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.db.DBType;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Session;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.io.unsync.UnsyncByteArrayInputStream;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.File;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.techsocialist.servicebuilder.model.VideoRegisterEntry;
import com.techsocialist.servicebuilder.model.VideoRegisterEntryContentBlobModel;
import com.techsocialist.servicebuilder.service.VideoRegisterEntryLocalService;
import com.techsocialist.servicebuilder.service.persistence.ProductionHouseRegisterEntryPersistence;
import com.techsocialist.servicebuilder.service.persistence.VideoRegisterEntryPersistence;

import java.io.InputStream;
import java.io.Serializable;

import java.sql.Blob;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the video register entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.techsocialist.servicebuilder.service.impl.VideoRegisterEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.techsocialist.servicebuilder.service.impl.VideoRegisterEntryLocalServiceImpl
 * @generated
 */
public abstract class VideoRegisterEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   VideoRegisterEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>VideoRegisterEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.techsocialist.servicebuilder.service.VideoRegisterEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the video register entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param videoRegisterEntry the video register entry
	 * @return the video register entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public VideoRegisterEntry addVideoRegisterEntry(
		VideoRegisterEntry videoRegisterEntry) {

		videoRegisterEntry.setNew(true);

		return videoRegisterEntryPersistence.update(videoRegisterEntry);
	}

	/**
	 * Creates a new video register entry with the primary key. Does not add the video register entry to the database.
	 *
	 * @param id the primary key for the new video register entry
	 * @return the new video register entry
	 */
	@Override
	@Transactional(enabled = false)
	public VideoRegisterEntry createVideoRegisterEntry(long id) {
		return videoRegisterEntryPersistence.create(id);
	}

	/**
	 * Deletes the video register entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the video register entry
	 * @return the video register entry that was removed
	 * @throws PortalException if a video register entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public VideoRegisterEntry deleteVideoRegisterEntry(long id)
		throws PortalException {

		return videoRegisterEntryPersistence.remove(id);
	}

	/**
	 * Deletes the video register entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param videoRegisterEntry the video register entry
	 * @return the video register entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public VideoRegisterEntry deleteVideoRegisterEntry(
		VideoRegisterEntry videoRegisterEntry) {

		return videoRegisterEntryPersistence.remove(videoRegisterEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			VideoRegisterEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return videoRegisterEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.techsocialist.servicebuilder.model.impl.VideoRegisterEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return videoRegisterEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.techsocialist.servicebuilder.model.impl.VideoRegisterEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return videoRegisterEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return videoRegisterEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return videoRegisterEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public VideoRegisterEntry fetchVideoRegisterEntry(long id) {
		return videoRegisterEntryPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the video register entry with the primary key.
	 *
	 * @param id the primary key of the video register entry
	 * @return the video register entry
	 * @throws PortalException if a video register entry with the primary key could not be found
	 */
	@Override
	public VideoRegisterEntry getVideoRegisterEntry(long id)
		throws PortalException {

		return videoRegisterEntryPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			videoRegisterEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(VideoRegisterEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			videoRegisterEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(VideoRegisterEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			videoRegisterEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(VideoRegisterEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return videoRegisterEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return videoRegisterEntryLocalService.deleteVideoRegisterEntry(
			(VideoRegisterEntry)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return videoRegisterEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the video register entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.techsocialist.servicebuilder.model.impl.VideoRegisterEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of video register entries
	 * @param end the upper bound of the range of video register entries (not inclusive)
	 * @return the range of video register entries
	 */
	@Override
	public List<VideoRegisterEntry> getVideoRegisterEntries(
		int start, int end) {

		return videoRegisterEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of video register entries.
	 *
	 * @return the number of video register entries
	 */
	@Override
	public int getVideoRegisterEntriesCount() {
		return videoRegisterEntryPersistence.countAll();
	}

	/**
	 * Updates the video register entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param videoRegisterEntry the video register entry
	 * @return the video register entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public VideoRegisterEntry updateVideoRegisterEntry(
		VideoRegisterEntry videoRegisterEntry) {

		return videoRegisterEntryPersistence.update(videoRegisterEntry);
	}

	@Override
	public VideoRegisterEntryContentBlobModel getContentBlobModel(
		Serializable primaryKey) {

		Session session = null;

		try {
			session = videoRegisterEntryPersistence.openSession();

			return (VideoRegisterEntryContentBlobModel)session.get(
				VideoRegisterEntryContentBlobModel.class, primaryKey);
		}
		catch (Exception exception) {
			throw videoRegisterEntryPersistence.processException(exception);
		}
		finally {
			videoRegisterEntryPersistence.closeSession(session);
		}
	}

	@Override
	@Transactional(readOnly = true)
	public InputStream openContentInputStream(long id) {
		try {
			VideoRegisterEntryContentBlobModel
				VideoRegisterEntryContentBlobModel = getContentBlobModel(id);

			Blob blob = VideoRegisterEntryContentBlobModel.getContentBlob();

			if (blob == null) {
				return _EMPTY_INPUT_STREAM;
			}

			InputStream inputStream = blob.getBinaryStream();

			if (_useTempFile) {
				inputStream = new AutoDeleteFileInputStream(
					_file.createTempFile(inputStream));
			}

			return inputStream;
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Activate
	protected void activate() {
		DB db = DBManagerUtil.getDB();

		if ((db.getDBType() != DBType.DB2) &&
			(db.getDBType() != DBType.MYSQL) &&
			(db.getDBType() != DBType.MARIADB) &&
			(db.getDBType() != DBType.SYBASE)) {

			_useTempFile = true;
		}
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			VideoRegisterEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		videoRegisterEntryLocalService =
			(VideoRegisterEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return VideoRegisterEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return VideoRegisterEntry.class;
	}

	protected String getModelClassName() {
		return VideoRegisterEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				videoRegisterEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ProductionHouseRegisterEntryPersistence
		productionHouseRegisterEntryPersistence;

	protected VideoRegisterEntryLocalService videoRegisterEntryLocalService;

	@Reference
	protected VideoRegisterEntryPersistence videoRegisterEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected File _file;

	private static final InputStream _EMPTY_INPUT_STREAM =
		new UnsyncByteArrayInputStream(new byte[0]);

	private boolean _useTempFile;

}